services:
  db_host:
    container_name: just_db
    image: postgres:16.2
    env_file:
      - "../../bots/sarbot/.env"
    ports:
      - "60607:5432"
    restart: always
    networks:
      - botnet
    volumes:
      - pgdata:/var/lib/postgres/data
      - ./backups:/backups
#    command:  docker-compose exec db_host sh ЭТО ВЫПОЛНИТЬ ПОСЛЕ СОЗДАНИЯ ВРУЧНУЮ, ШОБ АЛХИМИЯ НАШЛА КУДА ПОДКЛЮЧАТЬСЯ
#      - psql CREATE DATABASE nfull_db

volumes:
  pgdata:

networks:
  botnet:
    driver:
      bridge
