#FROM python:3.11.5-alpine3.18
#
#RUN apk update && \
#    apk add musl-dev libpq-dev gcc
#
#WORKDIR bots
#
#COPY bots/pollbot/requirements.txt bots/pollbot/requirements.txt
#
#RUN pip install -r bots/pollbot/requirements.txt
#
#CMD ["python", "poll_main.py"]
